spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elit_class
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "Elit_Class_secret_key_my_dinner_is_ZZimDack_SEXYFOOD"