plugins {
    id 'java'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}


group = 'org.elitclass'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}
repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    runtimeOnly 'com.mysql:mysql-connector-j'
}

test {
    useJUnitPlatform()
}

bootJar{
    enabled = false
}
jar{
    enabled = true
}